# Generated by Django 5.2.1 on 2025-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disease_predictor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseaseprediction",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diseaseprediction",
            name="prediction_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
