# Generated by Django 5.2.1 on 2025-05-26 14:48

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                blank=True, max_length=63, null=True
            ),
        ),
    ]
