# Generated by Django 5.2.1 on 2025-05-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussions", "0002_discussion_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="discussions.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
